name: Notify deps2.dev of new version

on:
  push:
    branches:
      - main

jobs:
  notify-deps2dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Read version from version.txt
      id: read_version
      run: |
        VERSION=$(cat version.txt)
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Notify deps2.dev of new version
      run: |
        curl -X POST "http://your-public-server-ip-or-domain:8000/newVersion" \
        -H "Content-Type: application/json" \
        -d '{"newVersion": "${{ env.version }}"}'


